################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions/mbfunccoils.c \
E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions/mbfuncdiag.c \
E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions/mbfuncdisc.c \
E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions/mbfuncholding.c \
E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions/mbfuncinput.c \
E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions/mbfuncother.c \
E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions/mbutils.c 

C_DEPS += \
./functions/mbfunccoils.d \
./functions/mbfuncdiag.d \
./functions/mbfuncdisc.d \
./functions/mbfuncholding.d \
./functions/mbfuncinput.d \
./functions/mbfuncother.d \
./functions/mbutils.d 

OBJS += \
./functions/mbfunccoils.o \
./functions/mbfuncdiag.o \
./functions/mbfuncdisc.o \
./functions/mbfuncholding.o \
./functions/mbfuncinput.o \
./functions/mbfuncother.o \
./functions/mbutils.o 


# Each subdirectory must supply rules for building sources it contributes
functions/mbfunccoils.o: E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions/mbfunccoils.c functions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../LIBJPEG/App -I../../LIBJPEG/Target -I../../Middlewares/Third_Party/LibJPEG/include -I../../TouchGFX/generated/videos/include -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/include" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/port" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/rtu" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
functions/mbfuncdiag.o: E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions/mbfuncdiag.c functions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../LIBJPEG/App -I../../LIBJPEG/Target -I../../Middlewares/Third_Party/LibJPEG/include -I../../TouchGFX/generated/videos/include -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/include" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/port" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/rtu" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
functions/mbfuncdisc.o: E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions/mbfuncdisc.c functions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../LIBJPEG/App -I../../LIBJPEG/Target -I../../Middlewares/Third_Party/LibJPEG/include -I../../TouchGFX/generated/videos/include -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/include" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/port" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/rtu" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
functions/mbfuncholding.o: E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions/mbfuncholding.c functions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../LIBJPEG/App -I../../LIBJPEG/Target -I../../Middlewares/Third_Party/LibJPEG/include -I../../TouchGFX/generated/videos/include -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/include" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/port" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/rtu" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
functions/mbfuncinput.o: E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions/mbfuncinput.c functions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../LIBJPEG/App -I../../LIBJPEG/Target -I../../Middlewares/Third_Party/LibJPEG/include -I../../TouchGFX/generated/videos/include -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/include" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/port" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/rtu" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
functions/mbfuncother.o: E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions/mbfuncother.c functions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../LIBJPEG/App -I../../LIBJPEG/Target -I../../Middlewares/Third_Party/LibJPEG/include -I../../TouchGFX/generated/videos/include -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/include" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/port" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/rtu" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
functions/mbutils.o: E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions/mbutils.c functions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../LIBJPEG/App -I../../LIBJPEG/Target -I../../Middlewares/Third_Party/LibJPEG/include -I../../TouchGFX/generated/videos/include -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/include" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/functions" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/port" -I"E:/LuanVanOnTheGo/TouchGFXProject/Touchgfx_mxide/Touch_mxide_v2/Middlewares/Third_Party/Modbus/rtu" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-functions

clean-functions:
	-$(RM) ./functions/mbfunccoils.d ./functions/mbfunccoils.o ./functions/mbfuncdiag.d ./functions/mbfuncdiag.o ./functions/mbfuncdisc.d ./functions/mbfuncdisc.o ./functions/mbfuncholding.d ./functions/mbfuncholding.o ./functions/mbfuncinput.d ./functions/mbfuncinput.o ./functions/mbfuncother.d ./functions/mbfuncother.o ./functions/mbutils.d ./functions/mbutils.o

.PHONY: clean-functions

